---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install common server packages
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - htop
    - vim
    - git
    - unzip
    - curl
